### ISSUE TITLE
Inline asm constraint for a sixteen bit value in XA?

### ISSUE THREAD

**Issue by davidgiven** [llvm-mos/llvm-mos#226] opened 2022-09-27 13:36 UTC
Is there one? The documentation page at https://llvm-mos.org/wiki/C_Inline_Assembly doesn't mention one, which seems surprising as values are (AFAIK) returned in XA.

If there isn't, could we have one? I have an API which uses XA extensively!

**Comment by davidgiven** [comment] 2022-09-27 21:16
Ah. I've just found out that pointers are passed differently (always in RS1). Presumably this is because they have to be in an imaginary register anyway to make them useful. How are pointers returned? The doc doesn't say.

**Comment by mysterymath** [comment] 2022-09-27 22:31
Pointers are returned using the same rules as passing args. This has been discussed as a feature before, but it would require some very heavy surgery to LLVM's inline assembly implementation. The workaround is to create a set of macros for passing a pair of arguments containing the low and high bytes of the value, then placing these values in X and A.

Duplicate of #88.

**Closed by mysterymath** 2022-09-27 22:31 UTC
