### ISSUE TITLE
Linker error with inline assembly: unable to translate instruction: call

### ISSUE THREAD

**Issue by rolandshacks** [llvm-mos/llvm-mos#283] opened 2023-02-05 07:53 UTC
### Occurance

Linker stage with optimizations turned off, works without problems when optimizhations are turned on.

- Project: https://github.com/rolandshacks/c64hacks
- Code fragements are using inline assembly, maybe that's an important indicator

### Example Code

This is is one example where inline assembly leads to issues, but when removing this fragment, the next inline assembly block leads to the same crash.

```

class Audio {
    public:
        static void init();
        static inline void update() {
            asm volatile (
                "jsr %0\n"
                ::
                "n"(sid_info.play_address)
            );
        }
};

```

### Error Message / Backtrace

LLVM ERROR: unable to translate instruction: call (in function: _ZN3sys5Audio6updateEv)
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: C:\\tools\\llvm-mos\\bin\\ld.lld d:\\Work\\github\\c64hacks\\build\\main.o d:\\Work\\github\\c64hacks\\build\\audio.o d:
\\Work\\github\\c64hacks\\build\\auxiliary.o d:\\Work\\github\\c64hacks\\build\\keyboard.o d:\\Work\\github\\c64hacks\\build\\system.o d:\\Work\\github\\c64hacks\\build\\video.o d:\\Work\\github\\c64hacks\\build\\music.o d:\\Work\\github\\c64hacks\\build\\sprites.o d:\\Work\\github\\c64hacks\\build\\tables.o -plugin-opt=O0 -mllvm -force-precise-rotation-cost -mllvm -jump-inst-cost=6 -mllvm -force-loop-cold-block -mllvm -phi-node-folding-threshold=0 -mllvm -two-entry-phi-node-folding-threshold=0 -mllvm -align-large-globals=false -mllvm -disable-spill-hoist -mllvm -lsr-complexity-limit=10000000 -mllvm -zp-avail=110 --gc-sections --sort-section=alignment -LC:\\tools\\llvm-mos\\bin/../mos-platform/c64/lib -LC:\\tools\\llvm-mos\\bin/../mos-platform/commodore/lib -LC:\\tools\\llvm-mos\\bin/../mos-platform/common/lib -l:crt0.o -lcrt0 -lcrt -lc -Tlink.ld -o d:\\Work\\github\\c64hacks\\build\\cppdemo.prg
1.      Running pass 'Function Pass Manager' on module 'ld-temp.o'.
2.      Running pass 'IRTranslator' on function
 '
```
@_ZN3sys5Audio6updateEv'
Exception Code: 0x80000003
 #0 0x00007ff7103a67f1 (C:\tools\llvm-mos\bin\ld.lld.exe+0x667f1)
 #1 0x00007ffd44f5e5f5 (C:\WINDOWS\System32\ucrtbase.dll+0x7e5f5)
 #2 0x00007ffd44f5f601 (C:\WINDOWS\System32\ucrtbase.dll+0x7f601)
 #3 0x00007ff71039c634 (C:\tools\llvm-mos\bin\ld.lld.exe+0x5c634)
 #4 0x00007ff710974c22 (C:\tools\llvm-mos\bin\ld.lld.exe+0x634c22)
 #5 0x00007ff710975cd4 (C:\tools\llvm-mos\bin\ld.lld.exe+0x635cd4)
 #6 0x00007ff710c1ad72 (C:\tools\llvm-mos\bin\ld.lld.exe+0x8dad72)
 #7 0x00007ff71182be20 (C:\tools\llvm-mos\bin\ld.lld.exe+0x14ebe20)
 #8 0x00007ff71182c018 (C:\tools\llvm-mos\bin\ld.lld.exe+0x14ec018)
 #9 0x00007ff71182c22e (C:\tools\llvm-mos\bin\ld.lld.exe+0x14ec22e)
#10 0x00007ff71182bb66 (C:\tools\llvm-mos\bin\ld.lld.exe+0x14ebb66)
#11 0x00007ff710be74f0 (C:\tools\llvm-mos\bin\ld.lld.exe+0x8a74f0)
#12 0x00007ff710be6e55 (C:\tools\llvm-mos\bin\ld.lld.exe+0x8a6e55)
#13 0x00007ff710be02a9 (C:\tools\llvm-mos\bin\ld.lld.exe+0x8a02a9)
#14 
0x00007ff710bdfa15 (C:\tools\llvm-mos\bin\ld.lld.exe+0x89fa15)
#15 0x00007ff7104c12cb (C:\tools\llvm-mos\bin\ld.lld.exe+0x1812cb)
#16 0x00007ff71045ddda (C:\tools\llvm-mos\bin\ld.lld.exe+0x11ddda)
#17 0x00007ff710476636 (C:\tools\llvm-mos\bin\ld.lld.exe+0x136636)
#18 0x00007ff710477800 (C:\tools\llvm-mos\bin\ld.lld.exe+0x137800)
#19 0x00007ff71047708d (C:\tools\llvm-mos\bin\ld.lld.exe+0x13708d)
#20 0x00007ff710372fc6 (C:\tools\llvm-mos\bin\ld.lld.exe+0x32fc6)
#21 0x00007ff710373153 (C:\tools\llvm-mos\bin\ld.lld.exe+0x33153)
#22 0x00007ff711902170 (C:\tools\llvm-mos\bin\ld.lld.exe+0x15c2170)
#23 0x00007ffd469e26bd (C:\WINDOWS\System32\KERNEL32.DLL+0x126bd)
#24 0x00007ffd4754dfb8 (C:\WINDOWS\SYSTEM32\ntdll.dll+0x5dfb8)
```

mos-clang++: error: ld.lld command failed due to signal (use -v to see invocation)
process exited with error 1

**Comment by mysterymath** [comment] 2023-02-05 21:17
Can you try building this with -fcrash-diagnostics=all? This should produce automatically produce a reproducer directory that collects together all of the necessary inputs, along with a script to reproduce them.

Otherwise, I'll try installing the VSCode extension and so forth, but it's usually preferable to have smaller, self-contained reproducers for compiler issues whenever possible.

**Comment by rolandshacks** [comment] 2023-02-05 22:14
Will try asap.
I already tried a bit, and problems are going away when not using the "n" constraint.
Use case: using"n" for passing an uint16_t to be used as target address for JSR.
When using a void* together with "g" or "o", ... , it compiles, but code does not work. What would be the right way to use an uint16_t to pass an address to inline asm?

**Comment by rolandshacks** [comment] 2023-02-05 22:15
Btw. problems can be reproduces quite simple... just try any inline asm and use some ::"n"(addr).

**Comment by rolandshacks** [comment] 2023-02-06 07:48
This is how to reproduce:
---- main.cpp ----
```

extern const short ext_address; // defined outside this compilation unit
const short address = 0x1234;   // defined locally
int main(void) {
    asm volatile (
        "jsr %0\n"
        ::
        "n"(ext_address) // <-- fails with 'ext_address', works with 'address'
    );
    return 0;
}

```
--- data.cpp ---
`
extern const short ext_address = 0x1234;
`

**Comment by rolandshacks** [comment] 2023-02-06 07:51
This is the produced compile_commands.json:

---
```

[
    {
        "directory": "C:/Users/Roland/AppData/Local/Programs/Microsoft VS Code",
        "arguments": [
            "--config",
            "mos-c64.cfg",
            "-o",
            "d:/Work/c64/newproject/build/data.o",
            "-c",
            "-std=gnu++20",
            "-g",
            "-fstandalone-debug",
            "-fno-limit-debug-info",
            "-fno-discard-value-names",
            "-fcrash-diagnostics=all",
            "-O0",
            "-DDEBUG",
            "-I",
            "d:/Work/c64/newproject",
            "-I",
            "C:/tools/llvm-mos/mos-platform/common/include",
            "-I",
            "C:/tools/llvm-mos/mos-platform/commodore/include",
            "-I",
            "C:/tools/llvm-mos/mos-platform/c64/include",
            "-I",
            "C:/tools/llvm-mos/lib/clang/16/include"
        ],
        "file": "d:/Work/c64/newproject/src/data.cpp"
    },
    {
        "directory": "C:/Users/Roland/AppData/Local/Programs/Microsoft VS Code",
        "arguments": [
            "--config",
            "mos-c64.cfg",
            "-o",
            "d:/Work/c64/newproject/build/main.o",
            "-c",
            "-std=gnu++20",
            "-g",
            "-fstandalone-debug",
            "-fno-limit-debug-info",
            "-fno-discard-value-names",
            "-fcrash-diagnostics=all",
            "-O0",
            "-DDEBUG",
            "-I",
            "d:/Work/c64/newproject",
            "-I",
            "C:/tools/llvm-mos/mos-platform/common/include",
            "-I",
            "C:/tools/llvm-mos/mos-platform/commodore/include",
            "-I",
            "C:/tools/llvm-mos/mos-platform/c64/include",
            "-I",
            "C:/tools/llvm-mos/lib/clang/16/include"
        ],
        "file": "d:/Work/c64/newproject/src/main.cpp"
    }
]

```

**Comment by rolandshacks** [comment] 2023-02-06 08:17
Here is the stack dump on a Linux platform:

```
compiling /home/roland/work/c64/clangbug/src/main.cpp
compiling /home/roland/work/c64/clangbug/src/data.cpp
linking /home/roland/work/c64/clangbug/build/example.prg
LLVM ERROR: unable to translate instruction: call (in function: main)
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /home/roland/llvm-mos/bin/ld.lld /home/roland/work/c64/clangbug/build/main.o /home/rola
nd/work/c64/clangbug/build/data.o -plugin-opt=O0 -plugin-opt=-crash-diagnostics-dir=/home/roland/work/c64/clangbug/build -mllvm -force-precise-rotation-cost -mllvm -jump-inst-cost=6 -mllvm -force-loop-cold-block -mllvm -phi-node-folding-threshold=0 -mllvm -two-entry-phi-node-folding-threshold=0 -mllvm -align-large-globals=false -mllvm -disable-spill-hoist -mllvm -lsr-complexity-limit=10000000 -mllvm 
-zp-avail=110 --gc-sections --sort-section=alignment -L/home/roland/llvm-mos/bin/../mos-platform/c64/lib -L/home/roland/llvm-mos/bin/../mos-platform/commodore/lib -L/home/roland/llvm-mos/bin/../mos-platform/common/lib -l:crt0.o -lcrt0 -lcrt -lc -Tlink.ld -o /home/roland/work/c64/clangbug/build/example.prg
1.      Running pass 'Function Pass Manager' on module 'ld-temp.o'.
2.      Running pass 'IRTranslator' on function '@main'
 #0 0x000056477531aa1b llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/roland/llvm-mos/bin/ld.lld+0x762a1b)
 #1 0x0000564775319639 llvm::sys::RunSignalHandlers() (/home/roland/llvm-mos/bin/ld.lld+0x761639)
 #2 0x0000564775319e2a SignalHandler(int) Signals.cpp:0:0
 #3 0x00007fedc2be2520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007fedc2c36a7c pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x96a7c)
#5 0x00007fedc2be2476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007fedc2bc87f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x00005647752e0816 llvm::report_fatal_error(llvm::Twine const&, bool) (/home/roland/llvm-mos/bin/ld.lld+0x728816)
 #8 0x000056477580c12d reportTranslationError(llvm::MachineFunction&, llvm::TargetPassConfig const&, llvm::OptimizationRemarkEmitter&, llvm::OptimizationRemarkMissed&) IRTranslator.cpp:0:0
 #9 0x000056477581c493 llvm::IRTranslator::runOnMachineFunction(llvm::MachineFunction&) (/home/roland/llvm-mos/bin/ld.lld+0xc64493)
#10 0x0000564775a7719b llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (.part.0) MachineFunctionPass.cpp:0:0
#11 0x0000564776643d80 llvm::FPPassManager::runOnFunction(llvm::Function&) (/home/roland/llvm-mos/bin/ld.lld+0x1a8bd80)
#12 0x0000564776643ef7 llvm::FPPassManager::runOnModule(llvm::Module&) (/home/roland/llvm-mos/bin/ld.lld+0x1a8bef7)
#13 0x00005647766445bc llvm::legacy::PassManagerImpl::run(llvm::Module&) (/home/roland/llvm-mos/bin/ld.lld+0x1a8c5bc)
#14 0x0000564775a0bf98 codegen(llvm::lto::Config const&, llvm::TargetMachine*, std::function<llvm::Expected<std::unique_ptr<llvm::CachedFileStream, std::default_delete<llvm::CachedFileStream>>> (unsigned int)>, unsigned int, llvm::Module&, llvm::ModuleSummaryIndex const&) LTOBackend.cpp:0:0
#15 0x0000564775a0c136 llvm::lto::backend(llvm::lto::Config const&, std::function<llvm::Expected<std::unique_ptr<llvm::CachedFileStream, std::default_delete<llvm::CachedFileStream>>> (unsigned int)>, unsigned int, llvm::Module&, llvm::ModuleSummaryIndex&) (/home/roland/llvm-mos/bin/ld.lld+0xe54136)
#16 0x0000564775a057cb llvm::lto::LTO::runRegularLTO(std::function<llvm::Expected<std::unique_ptr<llvm::CachedFileStream, std::default_delete<llvm::CachedFileStream>>> (unsigned int)>) (/home/roland/llvm-mos/bin/ld.lld+0xe4d7cb)
#17 0x0000564775a05ae8 llvm::lto::LTO::run(std::function<llvm::Expected<std::unique_ptr<llvm::CachedFileStream, std::default_delete<llvm::CachedFileStream>>> (unsigned int)>, std::function<llvm::Expected<std::function<llvm::Expected<std::unique_ptr<llvm::CachedFileStream, std::default_delete<llvm::CachedFileStream>>> (unsigned int)>> (unsigned int, llvm::StringRef)>) (/home/roland/llvm-mos/bin/ld.lld+0xe4dae8)
#18 0x0000564775402cae lld::elf::BitcodeCompiler::compile() (/home/roland/llvm-mos/bin/ld.lld+0x84acae)
#19 0x00005647753af7bc void lld::elf::LinkerDriver::compileBitcodeFiles<llvm::object::ELFType<(llvm::support::endianness)1, false>>(bool) (/home/roland/llvm-mos/bin/ld.lld+0x7f77bc)
#20 0x00005647753b5be7 lld::elf::LinkerDriver::link(llvm::opt::InputArgList&) (/home/roland/llvm-mos/bin/ld.lld+0x7fdbe7)
#21 0x00005647753bd8a7 lld::elf::LinkerDriver::linkerMain(llvm::ArrayRef<char const*>) (/home/roland/llvm-mos/bin/ld.lld+0x8058a7)
#22 0x00005647753be59e lld::elf::link(llvm::ArrayRef<char const*>, llvm::raw_ostream&, llvm::raw_ostream&, bool, bool) (/home/roland/llvm-mos/bin/ld.lld+0x80659e)
#23 0x00005647752cf0a1 lldMain(int, char const**, llvm::raw_ostream&, llvm::raw_ostream&, bool) lld.cpp:0:0
#24 0x00005647752cf1e2 lld_main(int, char**) (/home/roland/llvm-mos/bin/ld.lld+0x7171e2)
#25 0x00007fedc2bc9d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#26 0x00007fedc2bc9e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#27 0x00005647752cd7fe _start (/home/roland/llvm-mos/bin/ld.lld+0x7157fe)
clang-16: error: unable to execute command: Aborted (core dumped)
clang-16: error: ld.lld command failed due to signal (use -v to see invocation)

```

**Comment by mysterymath** [comment] 2023-02-06 17:09
Thanks for your help; I was able to reproduce this and diagnose it.

So, there's two problems here: how to actually do something like this, and why there wasn't an error message.

The first is simple; your code passes the *contents* of the external symbol, not it's address. That's why `i` isn't acceptable; the argument isn't a constant. You mean to say `&ext_address`, not `address`.

As for the error message, compiling this code snippet to x86 assembly produces this:
```
main.cpp:5:9: error: invalid operand for inline asm constraint 'i'
        "jsr %0\n"
        ^
1 error generated.
```

Note that that's not an error message for the use of `JSR`, but for the use of an external symbol for constraint `i`. It seems LLVM only supports `n` and `i` for constants and global variables in the same translation unit.

The reason we're not getting good error messages is because we're using GlobalISel, the new instruction selection framework, while other targets use SelectionDAG. The way it's currently implemented, GlobalISel is supposed to fall back to SelectionDAG in cases like this, so it doesn't emit its own error messages. We don't actually have a SelectionDAG implementation to fall back to though, so it just crashes unhelpfully. I'll see what it'd take to check if a fall back is available and to emit error messages if not, but it'd be a pretty hefty diff from upstream.

I'll leave this open for the error message; we should do better here if we can.

**Comment by rolandshacks** [comment] 2023-02-06 17:35
Hi. Thanks for picking this up so quickly!

I was fiddling around a bit further and also stumbled upon the missing address operator (forgotten &). Damn.

As there are plenty of workarounds available, I don't think this issue is in any sense high-prio. Writing asm modules might be the better choice for many things anyways.

Btw. I was optimizing a bit on that little demo I wrote using clang, ... looks there's plenty of things to further optimize on both sides ... the way to write code, and maybe the optimizer...

**Thanks again for working on this fantastic idea to build a modern compiler for 6502!**

**Comment by mysterymath** [comment] 2023-02-08 23:21
Closing as won'tfix for the error message. It looks like this will need substatial effort to do, and that should happen naturally upstream as work on GlobalISel continues.

**Closed by mysterymath** 2023-02-08 23:21 UTC
Labels: bug, p1
