### ISSUE TITLE
Compiler generates incorrect assembly code which then leads to infinite loop in runtime.

### ISSUE THREAD

**Issue by Andrew900460** [llvm-mos/llvm-mos#285] opened 2023-02-22 06:26 UTC

**Comment by mysterymath** [comment] 2023-02-22 18:21
I've narrowed this down a bit this morning; it has something to do with how the assembler backend emits NOPs to align code to 2-byte intervals. This is part of the Itanium C++ ABI that most targets (including ours) use for member functions. I'll have to step through this in the debugger in detail later and see what's going wrong.

**Comment by Andrew900460** [comment] 2023-02-22 19:47
Contex: When compiled with -fno-lto, the compiler will emit a "brk" instruction in the main function which causes the code to loop forever between 0x0000 and 0x0002, even though the main function has no code in it.

Happens with "mos-clang++ --config mos-sim.cfg -o [output file] -Os -fno-lto [main input cpp file]"

Offending Code:
```
#include <stdio.h>
#include <cstdint>

typedef unsigned char byte;
typedef uint16_t uint16;
typedef uint32_t uint32;
typedef uint64_t uint64;

volatile byte& ram8(const uint16 address) {
    return *reinterpret_cast<byte*>(address);
}

volatile uint16& ram16(const uint16 address) {
    return *reinterpret_cast<uint16*>(address);
}

volatile uint32& ram32(const uint16 address) {
    return *reinterpret_cast<uint32*>(address);
}

struct fixed16 {
	union {
		uint16 value;
		struct {
			byte frac;
			byte whole;
		};
	};

	// constexpr fixed16() : value(0) {}
	// constexpr explicit fixed16(const uint16& v) : value(v) {}
	// constexpr explicit fixed16(const uint16&& v) : value(v) {}
	// explicit fixed16(const byte whole, const byte frac): frac(frac), whole(whole) {}
	// fixed16(const fixed16& v) : value(v.value) {}

	char* to_string(char buffer[], const byte size);
	char* to_string();
};

char* fixed16::to_string(char buffer[], const byte size) {  // initial implementation, could obviously be better
	char offset = sprintf(buffer, "%u", whole);

	char i = offset;
	buffer[i++] = '.';

	if(frac==0) {
		buffer[i++] = '0';
	} else {
		uint16 fracTemp = frac;
		while (i < 16 && fracTemp != 0) {
			fracTemp *= 10;
			char digit = (fracTemp >> 8) + 48;
			fracTemp &= 0x00FF;
			buffer[i] = digit;
			i++;
		}
	}
	buffer[i] = 0;
	return buffer;
}

char* fixed16::to_string() {
	//char* output = RequestStringFromPool();
	//to_string(output,32);
	return 0;
}

unsigned int seed = 7;

unsigned int MyRand() {
	seed = seed * 11 + 40503;
	return seed;
}

void RunTests() {

}

int main() {
	return 0;
}
```

**Comment by mysterymath** [comment] 2023-02-23 03:16
It was a relatively simple oversight in the (surprisingly untested) code that emits NOPs to align code. It had `OS << 0xEA`, which emit 0xea000000, not 0xea as intended, since 0xea is an integer constant, not a char constant. 00 is the opcode for BRK, that's why it was showing up inside main.

**Comment by mysterymath** [comment] 2023-02-23 03:17
Closed by 3ec4753f

**Closed by mysterymath** 2023-02-23 03:17 UTC

**Comment by johnwbyrd** [comment] 2023-02-23 19:01
Sorry.  I remember writing that code.

**Comment by mysterymath** [comment] 2023-02-23 19:17
If it makes you feel any better, I've written that specific OS << int bug at least 3 times in upstream code by now. Everything promoting to int in C is a massively underappreciated footgun.
